/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ReliefTraceINInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "attestDelivery"
      | "attestDonation"
      | "attestSpend"
      | "campaignCount"
      | "campaigns"
      | "closeCampaign"
      | "createCampaign"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CampaignCreated"
      | "DeliveryAttested"
      | "DonationAttested"
      | "SpendAttested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "attestDelivery",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "attestDonation",
    values: [BigNumberish, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "attestSpend",
    values: [
      BigNumberish,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "campaignCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "campaigns",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "closeCampaign",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCampaign",
    values: [AddressLike, string, string, string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "attestDelivery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "attestDonation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "attestSpend",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "campaignCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "campaigns", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "closeCampaign",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCampaign",
    data: BytesLike
  ): Result;
}

export namespace CampaignCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    operator: AddressLike,
    disasterTag: string,
    darpanId: string,
    promiseHash: BytesLike,
    ts: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    operator: string,
    disasterTag: string,
    darpanId: string,
    promiseHash: string,
    ts: bigint
  ];
  export interface OutputObject {
    id: bigint;
    operator: string;
    disasterTag: string;
    darpanId: string;
    promiseHash: string;
    ts: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DeliveryAttestedEvent {
  export type InputTuple = [
    id: BigNumberish,
    spendRef: BytesLike,
    attestor: AddressLike,
    ts: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    spendRef: string,
    attestor: string,
    ts: bigint
  ];
  export interface OutputObject {
    id: bigint;
    spendRef: string;
    attestor: string;
    ts: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DonationAttestedEvent {
  export type InputTuple = [
    id: BigNumberish,
    utrHash: BytesLike,
    donorRef: BytesLike,
    amountPaise: BigNumberish,
    ts: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    utrHash: string,
    donorRef: string,
    amountPaise: bigint,
    ts: bigint
  ];
  export interface OutputObject {
    id: bigint;
    utrHash: string;
    donorRef: string;
    amountPaise: bigint;
    ts: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SpendAttestedEvent {
  export type InputTuple = [
    id: BigNumberish,
    spendRef: BytesLike,
    utrHash: BytesLike,
    vendorRef: BytesLike,
    amountPaise: BigNumberish,
    cat: BigNumberish,
    evidenceCID: string,
    memo: string,
    ts: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    spendRef: string,
    utrHash: string,
    vendorRef: string,
    amountPaise: bigint,
    cat: bigint,
    evidenceCID: string,
    memo: string,
    ts: bigint
  ];
  export interface OutputObject {
    id: bigint;
    spendRef: string;
    utrHash: string;
    vendorRef: string;
    amountPaise: bigint;
    cat: bigint;
    evidenceCID: string;
    memo: string;
    ts: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReliefTraceIN extends BaseContract {
  connect(runner?: ContractRunner | null): ReliefTraceIN;
  waitForDeployment(): Promise<this>;

  interface: ReliefTraceINInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  attestDelivery: TypedContractMethod<
    [id: BigNumberish, spendRef: BytesLike],
    [void],
    "nonpayable"
  >;

  attestDonation: TypedContractMethod<
    [
      id: BigNumberish,
      utrHash: BytesLike,
      donorRef: BytesLike,
      amountPaise: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  attestSpend: TypedContractMethod<
    [
      id: BigNumberish,
      utrHash: BytesLike,
      vendorRef: BytesLike,
      amountPaise: BigNumberish,
      cat: BigNumberish,
      evidenceCID: string,
      memo: string
    ],
    [string],
    "nonpayable"
  >;

  campaignCount: TypedContractMethod<[], [bigint], "view">;

  campaigns: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean
      ] & {
        operator: string;
        oracle: string;
        disasterTag: string;
        darpanId: string;
        reg80G: string;
        promiseHash: string;
        raisedPaise: bigint;
        spentPaise: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  closeCampaign: TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  createCampaign: TypedContractMethod<
    [
      oracle: AddressLike,
      disasterTag: string,
      darpanId: string,
      reg80G: string,
      promiseHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "attestDelivery"
  ): TypedContractMethod<
    [id: BigNumberish, spendRef: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "attestDonation"
  ): TypedContractMethod<
    [
      id: BigNumberish,
      utrHash: BytesLike,
      donorRef: BytesLike,
      amountPaise: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "attestSpend"
  ): TypedContractMethod<
    [
      id: BigNumberish,
      utrHash: BytesLike,
      vendorRef: BytesLike,
      amountPaise: BigNumberish,
      cat: BigNumberish,
      evidenceCID: string,
      memo: string
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "campaignCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "campaigns"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean
      ] & {
        operator: string;
        oracle: string;
        disasterTag: string;
        darpanId: string;
        reg80G: string;
        promiseHash: string;
        raisedPaise: bigint;
        spentPaise: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "closeCampaign"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createCampaign"
  ): TypedContractMethod<
    [
      oracle: AddressLike,
      disasterTag: string,
      darpanId: string,
      reg80G: string,
      promiseHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "CampaignCreated"
  ): TypedContractEvent<
    CampaignCreatedEvent.InputTuple,
    CampaignCreatedEvent.OutputTuple,
    CampaignCreatedEvent.OutputObject
  >;
  getEvent(
    key: "DeliveryAttested"
  ): TypedContractEvent<
    DeliveryAttestedEvent.InputTuple,
    DeliveryAttestedEvent.OutputTuple,
    DeliveryAttestedEvent.OutputObject
  >;
  getEvent(
    key: "DonationAttested"
  ): TypedContractEvent<
    DonationAttestedEvent.InputTuple,
    DonationAttestedEvent.OutputTuple,
    DonationAttestedEvent.OutputObject
  >;
  getEvent(
    key: "SpendAttested"
  ): TypedContractEvent<
    SpendAttestedEvent.InputTuple,
    SpendAttestedEvent.OutputTuple,
    SpendAttestedEvent.OutputObject
  >;

  filters: {
    "CampaignCreated(uint256,address,string,string,bytes32,uint256)": TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;
    CampaignCreated: TypedContractEvent<
      CampaignCreatedEvent.InputTuple,
      CampaignCreatedEvent.OutputTuple,
      CampaignCreatedEvent.OutputObject
    >;

    "DeliveryAttested(uint256,bytes32,address,uint256)": TypedContractEvent<
      DeliveryAttestedEvent.InputTuple,
      DeliveryAttestedEvent.OutputTuple,
      DeliveryAttestedEvent.OutputObject
    >;
    DeliveryAttested: TypedContractEvent<
      DeliveryAttestedEvent.InputTuple,
      DeliveryAttestedEvent.OutputTuple,
      DeliveryAttestedEvent.OutputObject
    >;

    "DonationAttested(uint256,bytes32,bytes32,uint256,uint256)": TypedContractEvent<
      DonationAttestedEvent.InputTuple,
      DonationAttestedEvent.OutputTuple,
      DonationAttestedEvent.OutputObject
    >;
    DonationAttested: TypedContractEvent<
      DonationAttestedEvent.InputTuple,
      DonationAttestedEvent.OutputTuple,
      DonationAttestedEvent.OutputObject
    >;

    "SpendAttested(uint256,bytes32,bytes32,bytes32,uint256,uint8,string,string,uint256)": TypedContractEvent<
      SpendAttestedEvent.InputTuple,
      SpendAttestedEvent.OutputTuple,
      SpendAttestedEvent.OutputObject
    >;
    SpendAttested: TypedContractEvent<
      SpendAttestedEvent.InputTuple,
      SpendAttestedEvent.OutputTuple,
      SpendAttestedEvent.OutputObject
    >;
  };
}
